-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE wsu_batchlist (
  wsubl_id SERIAL NOT NULL,
  wsubl_name VARCHAR(255) NOT NULL,
  wsubl_actor BIGINT NOT NULL,
  wsubl_createdat TIMESTAMPTZ NOT NULL,
  wsubl_status VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY(wsubl_id)
);

CREATE INDEX wsu_batchlist_actor ON wsu_batchlist (wsubl_actor);


CREATE TABLE wsu_batch (
  wsub_id SERIAL NOT NULL,
  wsub_batch INT NOT NULL,
  wsub_input TEXT NOT NULL,
  wsub_output TEXT DEFAULT NULL,
  PRIMARY KEY(wsub_id)
);

CREATE INDEX wsu_batch_batch ON wsu_batch (wsub_batch);
