generate:
	php ../../../maintenance/generateSchemaSql.php --json tables.json --type=mysql --sql=mysql/tables-generated.sql
	php ../../../maintenance/generateSchemaSql.php --json tables.json --type=sqlite --sql=sqlite/tables-generated.sql
	php ../../../maintenance/generateSchemaSql.php --json tables.json --type=postgres --sql=postgres/tables-generated.sql
